name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set a variable
        run: echo "MY_VAR=`date`" >> $GITHUB_ENV
      - name: Check variable
        run: |
          echo $MY_VAR
      - name: Print env
          env
